/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace FunditContract {
  export type InsuranceContractStruct = {
    id: BigNumberish;
    proposalId: BigNumberish;
    bidId: BigNumberish;
    user: AddressLike;
    company: AddressLike;
    monthlyPremium: BigNumberish;
    contractPeriod: BigNumberish;
    startDate: BigNumberish;
    autoPayment: boolean;
    status: BigNumberish;
  };

  export type InsuranceContractStructOutput = [
    id: bigint,
    proposalId: bigint,
    bidId: bigint,
    user: string,
    company: string,
    monthlyPremium: bigint,
    contractPeriod: bigint,
    startDate: bigint,
    autoPayment: boolean,
    status: bigint
  ] & {
    id: bigint;
    proposalId: bigint;
    bidId: bigint;
    user: string;
    company: string;
    monthlyPremium: bigint;
    contractPeriod: bigint;
    startDate: bigint;
    autoPayment: boolean;
    status: bigint;
  };
}

export interface FunditContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confirmContract"
      | "contracts"
      | "contractsByCompany"
      | "contractsByUser"
      | "getAllContracts"
      | "getContract"
      | "getContractsByCompany"
      | "getContractsByUser"
      | "nextContractId"
      | "toggleAutoPayment"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AutoPaymentToggled" | "ContractConfirmed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confirmContract",
    values: [
      BigNumberish,
      BigNumberish,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "contracts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contractsByCompany",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contractsByUser",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContract",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractsByCompany",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractsByUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextContractId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "toggleAutoPayment",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "confirmContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "contracts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contractsByCompany",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractsByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractsByCompany",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractsByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextContractId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleAutoPayment",
    data: BytesLike
  ): Result;
}

export namespace AutoPaymentToggledEvent {
  export type InputTuple = [contractId: BigNumberish, enabled: boolean];
  export type OutputTuple = [contractId: bigint, enabled: boolean];
  export interface OutputObject {
    contractId: bigint;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractConfirmedEvent {
  export type InputTuple = [
    contractId: BigNumberish,
    user: AddressLike,
    company: AddressLike
  ];
  export type OutputTuple = [contractId: bigint, user: string, company: string];
  export interface OutputObject {
    contractId: bigint;
    user: string;
    company: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FunditContract extends BaseContract {
  connect(runner?: ContractRunner | null): FunditContract;
  waitForDeployment(): Promise<this>;

  interface: FunditContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confirmContract: TypedContractMethod<
    [
      _proposalId: BigNumberish,
      _bidId: BigNumberish,
      _user: AddressLike,
      _company: AddressLike,
      _monthlyPremium: BigNumberish,
      _contractPeriod: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  contracts: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        id: bigint;
        proposalId: bigint;
        bidId: bigint;
        user: string;
        company: string;
        monthlyPremium: bigint;
        contractPeriod: bigint;
        startDate: bigint;
        autoPayment: boolean;
        status: bigint;
      }
    ],
    "view"
  >;

  contractsByCompany: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  contractsByUser: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getAllContracts: TypedContractMethod<[], [bigint[]], "view">;

  getContract: TypedContractMethod<
    [_contractId: BigNumberish],
    [FunditContract.InsuranceContractStructOutput],
    "view"
  >;

  getContractsByCompany: TypedContractMethod<
    [_company: AddressLike],
    [bigint[]],
    "view"
  >;

  getContractsByUser: TypedContractMethod<
    [_user: AddressLike],
    [bigint[]],
    "view"
  >;

  nextContractId: TypedContractMethod<[], [bigint], "view">;

  toggleAutoPayment: TypedContractMethod<
    [_contractId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confirmContract"
  ): TypedContractMethod<
    [
      _proposalId: BigNumberish,
      _bidId: BigNumberish,
      _user: AddressLike,
      _company: AddressLike,
      _monthlyPremium: BigNumberish,
      _contractPeriod: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "contracts"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        id: bigint;
        proposalId: bigint;
        bidId: bigint;
        user: string;
        company: string;
        monthlyPremium: bigint;
        contractPeriod: bigint;
        startDate: bigint;
        autoPayment: boolean;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "contractsByCompany"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "contractsByUser"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllContracts"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getContract"
  ): TypedContractMethod<
    [_contractId: BigNumberish],
    [FunditContract.InsuranceContractStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContractsByCompany"
  ): TypedContractMethod<[_company: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getContractsByUser"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "nextContractId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "toggleAutoPayment"
  ): TypedContractMethod<[_contractId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "AutoPaymentToggled"
  ): TypedContractEvent<
    AutoPaymentToggledEvent.InputTuple,
    AutoPaymentToggledEvent.OutputTuple,
    AutoPaymentToggledEvent.OutputObject
  >;
  getEvent(
    key: "ContractConfirmed"
  ): TypedContractEvent<
    ContractConfirmedEvent.InputTuple,
    ContractConfirmedEvent.OutputTuple,
    ContractConfirmedEvent.OutputObject
  >;

  filters: {
    "AutoPaymentToggled(uint256,bool)": TypedContractEvent<
      AutoPaymentToggledEvent.InputTuple,
      AutoPaymentToggledEvent.OutputTuple,
      AutoPaymentToggledEvent.OutputObject
    >;
    AutoPaymentToggled: TypedContractEvent<
      AutoPaymentToggledEvent.InputTuple,
      AutoPaymentToggledEvent.OutputTuple,
      AutoPaymentToggledEvent.OutputObject
    >;

    "ContractConfirmed(uint256,address,address)": TypedContractEvent<
      ContractConfirmedEvent.InputTuple,
      ContractConfirmedEvent.OutputTuple,
      ContractConfirmedEvent.OutputObject
    >;
    ContractConfirmed: TypedContractEvent<
      ContractConfirmedEvent.InputTuple,
      ContractConfirmedEvent.OutputTuple,
      ContractConfirmedEvent.OutputObject
    >;
  };
}
