/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace FunditProposal {
  export type ProposalStruct = {
    id: BigNumberish;
    proposer: AddressLike;
    title: string;
    description: string;
    mandatoryRequirements: string[];
    enrollmentConditions: string[];
    optionalFeatures: string[];
    desiredStartDate: BigNumberish;
    minPremium: BigNumberish;
    maxPremium: BigNumberish;
    createdAt: BigNumberish;
    status: BigNumberish;
    bidCount: BigNumberish;
  };

  export type ProposalStructOutput = [
    id: bigint,
    proposer: string,
    title: string,
    description: string,
    mandatoryRequirements: string[],
    enrollmentConditions: string[],
    optionalFeatures: string[],
    desiredStartDate: bigint,
    minPremium: bigint,
    maxPremium: bigint,
    createdAt: bigint,
    status: bigint,
    bidCount: bigint
  ] & {
    id: bigint;
    proposer: string;
    title: string;
    description: string;
    mandatoryRequirements: string[];
    enrollmentConditions: string[];
    optionalFeatures: string[];
    desiredStartDate: bigint;
    minPremium: bigint;
    maxPremium: bigint;
    createdAt: bigint;
    status: bigint;
    bidCount: bigint;
  };
}

export interface FunditProposalInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "closeProposal"
      | "createProposal"
      | "getActiveProposals"
      | "getProposal"
      | "getProposalCount"
      | "getProposalsByUser"
      | "incrementBidCount"
      | "proposals"
      | "userProposals"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ProposalClosed" | "ProposalCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "closeProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createProposal",
    values: [
      string,
      string,
      string[],
      string[],
      string[],
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveProposals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalsByUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "incrementBidCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userProposals",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "closeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalsByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "incrementBidCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userProposals",
    data: BytesLike
  ): Result;
}

export namespace ProposalClosedEvent {
  export type InputTuple = [proposalId: BigNumberish];
  export type OutputTuple = [proposalId: bigint];
  export interface OutputObject {
    proposalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [proposalId: BigNumberish, proposer: AddressLike];
  export type OutputTuple = [proposalId: bigint, proposer: string];
  export interface OutputObject {
    proposalId: bigint;
    proposer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FunditProposal extends BaseContract {
  connect(runner?: ContractRunner | null): FunditProposal;
  waitForDeployment(): Promise<this>;

  interface: FunditProposalInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  closeProposal: TypedContractMethod<
    [_proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createProposal: TypedContractMethod<
    [
      _title: string,
      _description: string,
      _mandatoryRequirements: string[],
      _enrollmentConditions: string[],
      _optionalFeatures: string[],
      _desiredStartDate: BigNumberish,
      _minPremium: BigNumberish,
      _maxPremium: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getActiveProposals: TypedContractMethod<
    [],
    [FunditProposal.ProposalStructOutput[]],
    "view"
  >;

  getProposal: TypedContractMethod<
    [_proposalId: BigNumberish],
    [FunditProposal.ProposalStructOutput],
    "view"
  >;

  getProposalCount: TypedContractMethod<[], [bigint], "view">;

  getProposalsByUser: TypedContractMethod<
    [_user: AddressLike],
    [FunditProposal.ProposalStructOutput[]],
    "view"
  >;

  incrementBidCount: TypedContractMethod<
    [_proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  proposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        proposer: string;
        title: string;
        description: string;
        desiredStartDate: bigint;
        minPremium: bigint;
        maxPremium: bigint;
        createdAt: bigint;
        status: bigint;
        bidCount: bigint;
      }
    ],
    "view"
  >;

  userProposals: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "closeProposal"
  ): TypedContractMethod<[_proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createProposal"
  ): TypedContractMethod<
    [
      _title: string,
      _description: string,
      _mandatoryRequirements: string[],
      _enrollmentConditions: string[],
      _optionalFeatures: string[],
      _desiredStartDate: BigNumberish,
      _minPremium: BigNumberish,
      _maxPremium: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getActiveProposals"
  ): TypedContractMethod<[], [FunditProposal.ProposalStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [_proposalId: BigNumberish],
    [FunditProposal.ProposalStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProposalCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProposalsByUser"
  ): TypedContractMethod<
    [_user: AddressLike],
    [FunditProposal.ProposalStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "incrementBidCount"
  ): TypedContractMethod<[_proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        proposer: string;
        title: string;
        description: string;
        desiredStartDate: bigint;
        minPremium: bigint;
        maxPremium: bigint;
        createdAt: bigint;
        status: bigint;
        bidCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "userProposals"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "ProposalClosed"
  ): TypedContractEvent<
    ProposalClosedEvent.InputTuple,
    ProposalClosedEvent.OutputTuple,
    ProposalClosedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;

  filters: {
    "ProposalClosed(uint256)": TypedContractEvent<
      ProposalClosedEvent.InputTuple,
      ProposalClosedEvent.OutputTuple,
      ProposalClosedEvent.OutputObject
    >;
    ProposalClosed: TypedContractEvent<
      ProposalClosedEvent.InputTuple,
      ProposalClosedEvent.OutputTuple,
      ProposalClosedEvent.OutputObject
    >;

    "ProposalCreated(uint256,address)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
  };
}
