/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FunditBid } from "./FunditBid";
export type { FunditContract } from "./FunditContract";
export type { FunditProposal } from "./FunditProposal";
export type { FunditToken } from "./FunditToken";
