/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as funditContractSol from "./FunditContract.sol";
export type { funditContractSol };
export type { FunditBid } from "./FunditBid";
export type { FunditProposal } from "./FunditProposal";
export type { FunditToken } from "./FunditToken";
