/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FunditContract__factory } from "./FunditContract__factory";
export { IFunditBid__factory } from "./IFunditBid__factory";
