/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IFunditBidInterface extends Interface {
  getFunction(nameOrSignature: "bidVoteCounts" | "getBid"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "bidVoteCounts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBid",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "bidVoteCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBid", data: BytesLike): Result;
}

export interface IFunditBid extends BaseContract {
  connect(runner?: ContractRunner | null): IFunditBid;
  waitForDeployment(): Promise<this>;

  interface: IFunditBidInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bidVoteCounts: TypedContractMethod<[bidId: BigNumberish], [bigint], "view">;

  getBid: TypedContractMethod<
    [bidId: BigNumberish],
    [
      [bigint, bigint, string, bigint, bigint, bigint] & {
        id: bigint;
        proposalId: bigint;
        bidder: string;
        coverageOffer: bigint;
        premiumOffer: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bidVoteCounts"
  ): TypedContractMethod<[bidId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBid"
  ): TypedContractMethod<
    [bidId: BigNumberish],
    [
      [bigint, bigint, string, bigint, bigint, bigint] & {
        id: bigint;
        proposalId: bigint;
        bidder: string;
        coverageOffer: bigint;
        premiumOffer: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  filters: {};
}
